version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  #install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    #runtime-versions:
      #aws cli: 2.0
      # name: version
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
       #- aws s3 rm s3://prajna-bucket --recursive
      # - command
  build:
    commands:
    - mkdir json-files                    #create 'json-files' folder
    - mkdir demo-1-folder                 #create 'demo-1-folder' folder
    - mkdir demo-2-folder                 #create 'demo-2-folder' folder
    - mkdir demo-3-folder                 #create 'demo-3-folder' folder
    - cp **/*.json json-files.            #copy all the '.json' files that are in root folder as well as level-1-deep folder to 'json-files' folder
    - zip -r demo-1.zip demo-1            #zip 'demo-1' to 'demo-1.zip'
    - mv demo-1.zip demo-1-folder         #move 'demo-1.zip' to 'demo-1-folder'
    - zip -r demo-2.zip demo-2            #zip 'demo-2' to 'demo-2.zip'
    - mv demo-2.zip demo-2-folder         #move 'demo-2.zip' to 'demo-2-folder'
    - zip -r demo-3.zip demo-3            #zip 'demo-3' to 'demo-3.zip'
    - mv demo-3.zip demo-3-folder         #move 'demo-3.zip' to 'demo-3-folder'
    
    #- find . -type d -name 'demo-1' -exec cp -R '*.json' archive.zip \;
    #- find . -type d -name 'demo-2' -exec cp -R '*.json' archive.zip \;
    #- find . -type d -name 'demo-3' -exec cp -R '*.json' archive.zip \;
      
      
      
      # - command
  post_build:
    commands:
       - aws s3 sync json-files s3://prajna-bucket/json-folder/json-files   #sync 'json-files' folder to given s3 path
       - aws s3 sync demo-1-folder s3://prajna-bucket/folder2/demo-1-folder #sync 'demo-1-folder' folder to given s3 path
       - aws s3 sync demo-2-folder s3://prajna-bucket/folder3/demo-2-folder #sync 'demo-2-folder' folder to given s3 path
       - aws s3 sync demo-3-folder s3://prajna-bucket/folder4/demo-3-folder #sync 'demo-3-folder' folder to given s3 path
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
     #- '**/*'
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
